version: '3.8'

services:
  consumer:
    build: .
    container_name: saleshq-affiliate-consumer
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      KAFKA_BROKERS: kafka:29092
      KAFKA_CLIENT_ID: custom-pixel-analytics-consumer
      KAFKA_GROUP_ID: custom-pixel-analytics-consumer-group
      LOG_LEVEL: info
      LOG_FORMAT: json
      TOPIC_PREFIX: custom-pixel-analytics
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    network_mode: host
